"""Subject model added.

Revision ID: 068ed960c42d
Revises: 0a3173329d84
Create Date: 2022-02-27 13:16:16.349367

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '068ed960c42d'
down_revision = '0a3173329d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_title_code_uc', 'courses', type_='unique')
    op.create_table('subjects',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'code', name='_title_code_uc')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.add_column('courses', sa.Column('subject_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'courses', 'subjects', ['subject_id'], ['id'])
    op.drop_column('courses', 'code')
    op.drop_column('courses', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('code', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_unique_constraint('_title_code_uc', 'courses', ['title', 'code'])
    op.drop_column('courses', 'subject_id')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
