"""Course subject unique id.

Revision ID: 4abb4a83352c
Revises: 068ed960c42d
Create Date: 2022-03-03 08:08:49.778638

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4abb4a83352c'
down_revision = '068ed960c42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['subject_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
