"""course model title and code unique together.

Revision ID: 512905603c1c
Revises: 2182e73b670f
Create Date: 2022-02-09 14:08:41.101877

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '512905603c1c'
down_revision = '2182e73b670f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_title_code_uc', 'courses', ['title', 'code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_title_code_uc', 'courses', type_='unique')
    # ### end Alembic commands ###
